### ISSUE TITLE
Collision with unanchored objects + proximity with gravitational artifacts instantly unbuckle wheelchair users

### ISSUE THREAD

**Issue by tonotom1** [new-frontiers-14/frontier-station-14#2274] opened 2024-10-18 01:09 UTC
## Description
Characters in wheelchairs are put into a helpless state where they cannot stay in their wheelchair at all if their wheelchair is within the influence of a gravitational artifact

Wheelchair bound characters immediately unbuckle upon collision with any unanchored object (lockers, crates, atmos canisters)

**Reproduction**
-Create a character that is wheelchair bound
-Spawn or locate an unanchored object (crate, locker or atmos canister good example)
-Bump into it with your wheelchair

-Create or locate an artifact with a gravitational pull
-Put wheelchair-bound character into the influence of the artifact
-Attempt to re-buckle yourself to the wheelchair while in the influence of the artifact

**Screenshots**
Media may be added at a later date

**Additional context**
No additional context

**Comment by whatston3** [comment] 2024-10-31 23:25
Honestly, probably an issue with you being dragged separately from the wheelchair.
If I had to guess, it's an issue with vehicle code, probable solution is to up the buckle slop to 30 cm for this, the janicart and secway, see if it fixes it and call it a day if so.

**Comment by NafenX** [comment] 2024-11-19 13:40
This is the issue with wheelchairs that I've talked about a few times on the Discord. Or, well, one of the issues. Maybe I should have just raised the issue here instead of the feedback channel 😓 Fixing this would be a HUGE bump in quality of life for people who want to play a wheelchair-using character! It might even get my friend to play the game again. They're a wheelchair user IRL and were super excited to see representation in a video game, but actually playing as a wheelchair-bound character was literally hell.. moreso than what you'd expect.

**Comment by NafenX** [comment] 2024-11-19 15:06
Huh... Well they haven't played in a long while so maybe another change already fixed that part. My bad!

**Comment by whatston3** [comment] 2024-11-19 16:14
Closing this issue for now as I can't reproduce it.  Reopen if needed, ideally with reproducible steps.

**Closed by whatston3** 2024-11-19 16:14 UTC
Labels: Status: Untriaged
